name: blogi

services:
  backend:
    container_name: blogi-backend
    image: ghcr.io/haashemi/blogi-api
    networks: [back-tier, front-tier]
    ports: [5571:8080]
    volumes: [.env:/app/.env]
    restart: unless-stopped

  frontend:
    container_name: blogi-frontend
    image: ghcr.io/haashemi/blogi
    env_file: .env
    networks: [front-tier]
    ports: [5572:3000]
    restart: unless-stopped

  postgres:
    container_name: blogi-postgres
    image: postgres:16
    env_file: .env
    networks: [back-tier]
    volumes: [./.blogi/postgres:/var/lib/postgresql/data]
    restart: unless-stopped
    shm_size: 128mb
    ports: [5573:5432]

networks:
  back-tier:
  front-tier:
