version: 3

dotenv: [".env"]

tasks:
  sqlc:
    cmds:
      - docker run --rm -v .:/src -w /src sqlc/sqlc generate

  # Run dev version of the backend
  dev:
    cmds:
      - go run ./cmd/blogi

  # Run dev tools from docker compose
  dev-tools:
    cmds:
      - docker compose up postgres -d

  db-init:
    cmds:
      - docker exec -it blogi-postgres createdb -U postgres blogi
